function [fitresult, gof] = createPwLFit(x, G)
%CREATEFIT(X,G)
%  Create a fit.
%
%  Data for 'pwlfit' fit:
%      X Input : x
%      Y Output: G
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Dec-2016 23:12:25


%% Fit: 'pwlfit'.
[xData, yData] = prepareCurveData( x, G );

% Set up fittype and options.
ft = fittype( '(x<Q)*(a1*x+b1)+(x>Q)*(a2*x+b2)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0.4 -Inf -Inf -Inf -Inf];
opts.StartPoint = [0.950222048838355 0.0461713906311539 0.823457828327293 0.0971317812358475 0.694828622975817];
opts.Upper = [2.1 Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
if 0
    figure( 'Name', 'pwlfit' );
    h = plot( fitresult, xData, yData );
    legend( h, 'G vs. x', 'pwlfit', 'Location', 'NorthEast' );
    % Label axes
    xlabel x
    ylabel G
    grid on
end


