function stats = readStatsTable(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   STATS = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   STATS = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   stats = importfile('stats.dat', 2, 16);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/08/31 16:49:41

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: text (%s)
%	column4: double (%f)
%   column5: text (%s)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%s%f%s%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
stats = table(dataArray{1:end-1}, 'VariableNames', {'Run','Freq','RX_Ant_Type','RX_Ant_Gain','TX_Ant_Type','TX_Ant_Gain','Path_Gain_Poly_Slope','Path_Gain_Poly_YInt','Mean_K','Min_K','Max_K','Mean_Delay_ns','Min_Delay_ns','Max_Delay_ns','Mean_Delay_Spread_ns','Min_Delay_Spread_ns','Max_Delay_Spread_ns'});

