classdef MeasurementRunMetric < double
    enumeration
        Site (1)
        Freq (2)
        MetalCanyon (3)
        Polarization (4)
        CoordX (5)
        CoordY (6)
        LOS (7)
        RicianK (8)
        RMSDelaySpread (9)
        MeanDelay (10)
        MaxDelay (11)
        PathGain (12)
    end

    methods (Static)
        function names = getNames()
            names = { ...
                'Site', ...
                'Frequency', ...
                'MetalCanyon', ...
                'Polarization', ...
                'CoordX', ...
                'CoordY', ...
                'LOS', ...
                'RicianK', ...
                'RMSDelaySpread', ...
                'MeanDelay', ...
                'MaxDelay', ...
                'PathGain' };  
        end

        function types = getTypes()
            types = { ...
                'string', ...
                'double', ...
                'double', ...
                'string', ...
                'double', ...
                'double', ...
                'double', ...
                'double', ...
                'double', ...
                'double', ...
                'double', ...
                'double' };             
        end
    end

    methods 
        function s = getName(obj)
            s = MeasurementRunMetric.getNames{double(obj)};
        end
        
        function s = getType(obj)             
            s = MeasurementRunMetric.getTypes{double(obj)};            
        end
    end
end